/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Principal.java
 *
 * Created on 12-ene-2009, 22:54:12
 */

package interfazGraficaCompilador;

import java.awt.Cursor;
import java.awt.Point;
import javax.swing.JLabel;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;

/**
 *
 * @author Administrador
 */
public class Principal extends javax.swing.JPanel {

    private Marco marco;
    /** Creates new form Principal */
    public Principal(Marco marco) {
        initComponents();
        linea.setText("linea: 1 columna: 0");
        this.marco = marco;
        programa.setSize(1000,600);
        programa.addCaretListener(
                new CaretListener(){
            public void caretUpdate(CaretEvent caretEvent){
                int numlinea, numColumna = 1;
                try{
                    int cursor = programa.getCaretPosition();
                    numlinea = programa.getLineOfOffset(cursor);
                    numColumna = cursor-programa.getLineStartOffset(numlinea);
                    numlinea++;
                    linea.setText("linea: " + numlinea + " columna: " + numColumna);
                }
                catch(Exception e){
                    e.printStackTrace();
                }

            }
        });

        //compilacion.setSize(300,200);
    }
    public JLabel getLinea(){
        return linea;
    }
    /*public Principal(Marco marco){
        initComponents();
        this.marco = marco;
        programa.setSize(1000,1000);
        compilacion.setSize(300,200);
    }*/
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        compilacion = new java.awt.TextArea();
        linea = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        programa = new javax.swing.JTextArea();

        compilacion.setEditable(false);

        linea.setText("jLabel1");

        programa.setColumns(20);
        programa.setRows(5);
        programa.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                programaCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        programa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                programaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(programa);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(compilacion, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(306, 306, 306)
                        .add(linea, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 133, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 304, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(51, 51, 51)
                .add(linea, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(19, 19, 19)
                .add(compilacion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void programaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_programaMouseClicked
               //programa.addCaretListener(listener);
    }//GEN-LAST:event_programaMouseClicked

    private void programaCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_programaCaretPositionChanged
         programa.addCaretListener( new CaretListener(){
            public void caretUpdate(CaretEvent caretEvent){
                int numlinea, numColumna = 1;

                try{
                    int cursor = programa.getCaretPosition();
                    numlinea = programa.getLineOfOffset(cursor);
                    numColumna = cursor-programa.getLineStartOffset(numlinea);
                    numlinea++;
                    linea.setText("linea: " + numlinea + " columna: " + numColumna);
                }
                catch(Exception e){
                    e.printStackTrace();
                }

            }
        });
    }//GEN-LAST:event_programaCaretPositionChanged
    public void escribirCompilacion(String text){
        compilacion.setText(text);
    }

    public void escribirPrograma(String text){
        programa.setText(text);
    }

    public String getCompilacion(){
        return this.compilacion.getText();
    }

    public String getPrograma(){
        
        System.out.println(programa.getText());
        
        return this.programa.getText();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextArea compilacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel linea;
    private javax.swing.JTextArea programa;
    // End of variables declaration//GEN-END:variables

}
