/*
 * Marco.java
 *
 * Created on 25 de noviembre de 2008, 15:41
 */

package Interfaz.TablaSimbolos;


import TablaSimbolos.TablaSimbolos;
import javax.swing.JOptionPane;

/**
 *
 * @author  Administrador
 */
public class MarcoTabla extends javax.swing.JFrame {
    
    /** Creates new form Marco */
    TablaSimbolos tabla = null;
    InsertarToken insertar;
    Simular simular;
    
    public MarcoTabla(TablaSimbolos tabla) {
        initComponents();
        this.tabla = tabla;
       Simular simular = new Simular(this);
       simular.setSize(1100,600);
       this.setSize(1100,600);
        this.setContentPane(simular);
        
    }
    
    public TablaSimbolos getTabla()
    {
        return tabla;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tabla Símbolos");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 583, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
